using Spectre.Console;
using System;
using System.Collections.Generic;
using System.Text;

namespace ArchGen.Cli.Generators
{
    public static class GitIntegration
    {
        public static void TryInitializeAndPublish(string solutionDirectory, string projectName)
        {
            if (!IsToolAvailable("git"))
            {
                AnsiConsole.MarkupLine("[yellow]Warning:[/] 'git' is not installed — skipping git initialization.");
                return;
            }

            if (!IsToolAvailable("gh"))
            {
                AnsiConsole.MarkupLine("[yellow]Warning:[/] GitHub CLI ('gh') is not installed — skipping GitHub publish.");
                return;
            }

            if (!IsGhAuthenticated())
            {
                AnsiConsole.MarkupLine("[yellow]Warning:[/] 'gh' is not authenticated (run 'gh auth login') — skipping GitHub publish.");
                return;
            }

            try
            {
                ProcessRunner.Run("git", "init", solutionDirectory);
                ProcessRunner.Run("git", "add .", solutionDirectory);
                ProcessRunner.Run("git", "commit -m \"Initial commit generated by archgen\"", solutionDirectory);

                var visibility = AnsiConsole.Prompt(
                    new SelectionPrompt<string>()
                        .Title($"GitHub repository visibility for [bold]{projectName}[/]:")
                        .AddChoices("Public", "Private"));

                var visibilityFlag = visibility == "Public" ? "--public" : "--private";

                ProcessRunner.Run(
                    "gh", $"repo create {projectName} --source=. {visibilityFlag} --push", solutionDirectory);

                AnsiConsole.MarkupLine("[green]GitHub repository created and pushed.[/]");
            }
            catch (Exception ex)
            {
                AnsiConsole.MarkupLine($"[yellow]Warning:[/] could not publish to GitHub: {ex.Message}");
            }
        }

        private static bool IsToolAvailable(string toolName)
        {
            try
            {
                ProcessRunner.Run(toolName, "--version", Directory.GetCurrentDirectory());
                return true;
            }
            catch
            {
                return false;
            }
        }

        private static bool IsGhAuthenticated()
        {
            try
            {
                ProcessRunner.Run("gh", "auth status", Directory.GetCurrentDirectory());
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
